### ISSUE TITLE
شمسی سازی

### ISSUE THREAD

**Issue by haselih2** [damavandon/persian-daterangepicker#1]
سلام
وقت بخیر
امکان انجام شمسی سازی یک دیت پیکر که بر اساس نسخه شما هست
توسط شما وجود داره؟

**Comment by damavandon** [comment]
> سلام وقت بخیر امکان انجام شمسی سازی یک دیت پیکر که بر اساس نسخه شما هست توسط شما وجود داره؟

سلام وقت بخیر
متوجه منظور شما نمیشم

**Comment by haselih2** [comment]
سلام
یک اسکریپت دارم

دیت پیکرش میلادی هست و با چیزی که شما نوشتین همخونی داره
کسی پیدا نکردم بتونه برام شمسی کنه
منظورم این بود با توجه به اینکه خودتون دیت پیکر شمسی ارائه دادین و چیزی هم که من نیاز دارم مطابق با نمونه شما هست

امکان انجام شمسی سازی وجود داره؟
هزینه و زمان بفرمایید
تشکر

**Comment by damavandon** [comment]
متاسفانه من وقت ندارم
شما می توانید .
اسکریت  به این ایمیل بفرستید.
به دوستان معرفی کنم اگر وقت داشتن انجام میدن
dev.mahditorkaman@gmail.com

**Comment by haselih2** [comment]
https://s31.picofile.com/file/8469049592/daterangepicker.zip.html

این دیت پیکر هست

تشکر

**Comment by damavandon** [comment]
ایمیل کنید
دوست عزیز
